services:
  mosquitto:
    build:
      context: .
      # args:
      #   - AUTH_METHOD=password
      #   - AUTH_USER=admin
      #   - AUTH_PASSWORD=admin
    volumes:
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883 # mqtt
      # - 9001:9001 # websockets

volumes:
  data:
    name: "mqtt-broker-data"
